"""
Regression tests for F2 Bundle Generator, Downstream Bank Consumption, and Corpus Fidelity.
Governing specification: construction/S2_CANDIDATE_SPEC_v0.11.md (§5.1, §5.5, §5.8, §11).

Strict Non-Circular Verification:
1. Expected logical GT is constructed strictly from pre-F8 sources (F5 bank + frozen scope/class layout).
2. Bundle bytes are generated independently by bundle_generator.
3. check_fidelity independently searches generated bytes, derives class from actual structure,
   reconstructs derived GT, and asserts derived_bytes == pre_f8_expected_bytes.
"""

import os
import sys
import json
import unittest
from typing import Dict, Any, List

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from f2_corpus.template_generator import (
    BankEntry,
    search_bundle_bytes_for_bank_entries,
    reconstruct_derived_ground_truth,
    serialize_ground_truth_canonically,
    check_fidelity,
)
from f2_corpus.bundle_generator import (
    load_bank_from_jsonl,
    generate_all_corpus_bundles,
)
from f2_corpus.class_assignment import get_class_name
from f2_corpus.constants import PARAMETERS, NUM_BUNDLES
from f3_protocol.canonical_serializer import (
    canonicalize_semantic_value,
    serialize_canonical_semantic_value_string,
)


def build_pre_f8_expected_ground_truth(
    bank_entries_by_bundle: Dict[int, List[BankEntry]],
    scope_table: Dict[str, Any],
    bundle_idx: int,
) -> Dict[str, Any]:
    """
    Construct expected logical GT record STRICTLY from pre-F8 sources:
    - frozen scope table
    - closed form class assignment (i + j) % 6
    - frozen F5 bank metadata
    Does NOT read generated bundle bytes or invoke reconstruction from bundle bytes.
    """
    expected: Dict[str, Any] = {}
    bundle_entries = bank_entries_by_bundle.get(bundle_idx, [])

    for p_idx, param in enumerate(PARAMETERS):
        scope = scope_table[param]["scopes"][bundle_idx]
        cls_name = get_class_name(bundle_idx, p_idx)

        # Look up matching bank entries for (param, scope)
        matching = [
            e for e in bundle_entries
            if e.parameter == param and e.scope == scope
        ]

        if cls_name in ("POS-EXPLICIT", "POS-BURIED"):
            det = [e for e in matching if e.semantic_role == "determining"][0]
            vc = "EXPLICIT_DOC" if det.evidence_stratum == "S-DOC" else "EXPLICIT_FILE"
            canon_val = canonicalize_semantic_value(det.semantic_value)
            readings = [{
                "entry_id": det.entry_id,
                "semantic_value": canon_val,
                "evidence_stratum": det.evidence_stratum,
                "exclusive_assertion": det.exclusive_assertion,
                "verbatim_excerpt": det.entry_text,
            }]
            support = [det.entry_id]

        elif cls_name == "AMBIG-CONSTRUCTED":
            det_list = [e for e in matching if e.semantic_role == "determining"]
            vc = "AMBIGUOUS"
            readings = [
                {
                    "entry_id": e.entry_id,
                    "semantic_value": canonicalize_semantic_value(e.semantic_value),
                    "evidence_stratum": e.evidence_stratum,
                    "exclusive_assertion": e.exclusive_assertion,
                    "verbatim_excerpt": e.entry_text,
                }
                for e in det_list
            ]
            def reading_sort_key(r: Dict[str, Any]) -> tuple:
                return (
                    serialize_canonical_semantic_value_string(r.get("semantic_value")),
                    str(r.get("entry_id", "")),
                    str(r.get("evidence_stratum", "")),
                    1 if r.get("exclusive_assertion") else 0,
                    str(r.get("verbatim_excerpt", "")),
                )
            readings.sort(key=reading_sort_key)
            support = sorted([e.entry_id for e in det_list])

        elif cls_name == "NEG-ADJACENT":
            adj = [e for e in matching if e.semantic_role == "non_determining_adjacent"][0]
            vc = "ABSENT"
            readings = []
            support = [adj.entry_id]

        elif cls_name == "NA-CONSTRUCTED":
            na = [e for e in matching if e.semantic_role == "non_applicable"][0]
            vc = "NOT_APPLICABLE"
            readings = []
            support = [na.entry_id]

        elif cls_name == "NEG-ABSENT":
            vc = "ABSENT"
            readings = []
            support = []

        else:
            raise ValueError(f"Unknown class {cls_name}")

        expected[param] = {
            "bundle_idx": bundle_idx,
            "parameter": param,
            "scope": scope,
            "class": cls_name,
            "verdict_class": vc,
            "readings": readings,
            "support_entry_ids": support,
        }

    return expected


class TestF2BundleGenerator(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        base_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
        cls.bank_path = os.path.join(base_dir, "corpus", "f5_bank", "F5_BANK_ATTEMPT_03.jsonl")
        cls.scope_path = os.path.join(base_dir, "implementation", "f2_corpus", "frozen_scope_table.json")
        cls.bank_entries = load_bank_from_jsonl(cls.bank_path)

        with open(cls.scope_path, "r", encoding="utf-8") as f:
            cls.scope_table = json.load(f)

        # Index bank entries by bundle_idx
        cls.bank_by_bundle = {i: [] for i in range(NUM_BUNDLES)}
        with open(cls.bank_path, "r", encoding="utf-8") as f:
            for line in f:
                if not line.strip():
                    continue
                raw = json.loads(line)
                b_idx = raw["bundle_idx"]
                entry = BankEntry(
                    entry_id=raw["entry_id"],
                    parameter=raw["parameter"],
                    scope=raw["scope"],
                    evidence_stratum=raw["evidence_stratum"],
                    semantic_role=raw["semantic_role"],
                    semantic_value=raw.get("semantic_value"),
                    entry_text=raw["entry_text"],
                    exclusive_assertion=raw.get("exclusive_assertion", False),
                )
                setattr(entry, "class", raw["class"])
                cls.bank_by_bundle[b_idx].append(entry)

    def test_downstream_bank_consumption_exact_and_verbatim(self):
        """
        Verify downstream consumption of F5_BANK_ATTEMPT_03.jsonl by bundle generator:
        - All 330 entries consumed
        - Exactly once per entry (single-use invariant §5.5)
        - Inserted verbatim without paraphrase or mutation
        - Zero slot re-keying
        """
        corpus = generate_all_corpus_bundles(self.bank_path, self.scope_path)
        self.assertEqual(len(corpus), NUM_BUNDLES)

        seen_entry_ids = set()
        total_occurrences_found = 0

        for b_idx, (artifacts, manifest, records) in enumerate(corpus):
            # Check every realization record matches bank entry text verbatim
            for rec in records:
                self.assertNotIn(
                    rec.entry_id, seen_entry_ids,
                    f"Single-use violation: entry {rec.entry_id} realized more than once!"
                )
                seen_entry_ids.add(rec.entry_id)

                # Locate entry in original bank
                matching_bank = [e for e in self.bank_entries if e.entry_id == rec.entry_id]
                self.assertEqual(len(matching_bank), 1, f"Unknown entry {rec.entry_id}")
                bank_entry = matching_bank[0]

                # Verbatim check: entry_text in realization must equal bank entry text
                self.assertEqual(rec.entry_text, bank_entry.entry_text)

                # Check exact byte occurrence in artifact bytes
                comp_bytes = artifacts.get_component_bytes(rec.component)
                byte_slice = comp_bytes[rec.byte_start:rec.byte_end].decode("utf-8")
                self.assertEqual(
                    byte_slice, bank_entry.entry_text,
                    f"Byte span in {rec.component} does not match verbatim text for {rec.entry_id}"
                )

            # Independently search bundle bytes
            discovered = search_bundle_bytes_for_bank_entries(artifacts, self.bank_entries)
            total_occurrences_found += len(discovered)

        # Exactly 330 entries realized across the corpus
        self.assertEqual(len(seen_entry_ids), 330)
        self.assertEqual(total_occurrences_found, 330)

    def test_non_circular_fidelity_verification_all_30_bundles(self):
        """
        Strict non-circular test:
        1. pre-F8 expected GT is built purely from F5 bank + frozen layout.
        2. F8 bundle generator independently generates bundle bytes.
        3. check_fidelity verifies derived bytes from bundle search == pre-F8 expected bytes.
        """
        corpus = generate_all_corpus_bundles(self.bank_path, self.scope_path)

        for b_idx, (artifacts, manifest, records) in enumerate(corpus):
            # 1. Pre-F8 expected logical GT
            pre_f8_expected_gt = build_pre_f8_expected_ground_truth(
                self.bank_by_bundle, self.scope_table, b_idx
            )
            pre_f8_expected_bytes = serialize_ground_truth_canonically(pre_f8_expected_gt)

            # Build bundle_slots for checker invariant validation
            bundle_slots = {}
            for p_idx, param in enumerate(PARAMETERS):
                scope = self.scope_table[param]["scopes"][b_idx]
                cls_name = get_class_name(b_idx, p_idx)
                bundle_slots[param] = {
                    "scope": scope,
                    "class": cls_name,
                }

            # 2. check_fidelity evaluates generated artifacts against pre-F8 expected bytes
            res = check_fidelity(
                artifacts=artifacts,
                frozen_bank=self.bank_entries,
                sealed_ground_truth_bytes=pre_f8_expected_bytes,
                bundle_slots=bundle_slots,
                bundle_manifest=manifest,
                realization_index=records,
            )
            self.assertTrue(
                res["valid"],
                msg=f"Bundle {b_idx} non-circular fidelity check failed: {res.get('error')}"
            )

    def test_bundle_generation_and_fidelity_all_30_bundles(self):
        """
        Verify that all 30 bundles are generated, all 330 bank entries are placed,
        and check_fidelity passes 100% on every bundle against its independently
        reconstructed location-independent ground truth.
        """
        corpus = generate_all_corpus_bundles(self.bank_path, self.scope_path)
        self.assertEqual(len(corpus), NUM_BUNDLES)

        total_realization_records = 0

        # Load scope table
        import json
        with open(self.scope_path, "r", encoding="utf-8") as f:
            scope_table = json.load(f)

        for b_idx, (artifacts, manifest, records) in enumerate(corpus):
            total_realization_records += len(records)

            # Build bundle_slots for this bundle
            bundle_slots = {}
            for p_idx, param in enumerate(PARAMETERS):
                scope = scope_table[param]["scopes"][b_idx]
                cls_name = get_class_name(b_idx, p_idx)
                bundle_slots[param] = {
                    "scope": scope,
                    "class": cls_name,
                }

            # 1. Search bundle bytes
            discovered = search_bundle_bytes_for_bank_entries(artifacts, self.bank_entries)

            # 2. Reconstruct derived ground truth
            derived_gt = reconstruct_derived_ground_truth(
                discovered=discovered,
                bundle_slots=bundle_slots,
                artifacts=artifacts,
                bundle_idx=b_idx,
            )

            # Check that all 11 parameter cells are present in derived GT
            self.assertEqual(len(derived_gt), 11, f"Bundle {b_idx} must have 11 cells")

            # Check that class matches frozen closed form
            for p_idx, param in enumerate(PARAMETERS):
                expected_class = get_class_name(b_idx, p_idx)
                actual_class = derived_gt[param]["class"]
                self.assertEqual(
                    actual_class,
                    expected_class,
                    f"Bundle {b_idx} param {param}: derived class {actual_class} != expected {expected_class}",
                )

                # Check location independence (no component, byte_start, byte_end in readings)
                for r in derived_gt[param]["readings"]:
                    self.assertNotIn("component", r)
                    self.assertNotIn("byte_start", r)
                    self.assertNotIn("byte_end", r)

            # 3. Canonical serialization
            sealed_bytes = serialize_ground_truth_canonically(derived_gt)

            # 4. Check fidelity (including realization_index cross-check)
            res = check_fidelity(
                artifacts=artifacts,
                frozen_bank=self.bank_entries,
                sealed_ground_truth_bytes=sealed_bytes,
                bundle_slots=bundle_slots,
                bundle_manifest=manifest,
                realization_index=records,
            )
            self.assertTrue(res["valid"], msg=f"Bundle {b_idx} fidelity failed: {res.get('error')}")

        # Invariant: exactly 330 bank entries realized across the corpus
        self.assertEqual(total_realization_records, 330)


if __name__ == "__main__":
    unittest.main()
